### PR TITLE
fix: operate on Node instead of Element when obfuscating

### LINKED ISSUE #119: obfuscated style applied only on the last child of the component
[example](https://webui.adventure.kyori.net/?mode=chat_closed&input=%3Cred%3E%3Cobfuscated%3Eabc%3Cblue%3Ed%3Cgreen%3Eef&bg=grass)

If there are no children in the component, it works fine

### PR DESCRIPTION
**Pull request by rymiel**
Closes #119. This allows it to properly handle and modify text nodes without affecting children

### CODE REVIEW

File: src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt [hunk 1]
```diff
@@ -548,12 +549,14 @@ private fun obfuscateAll() {
...
-    } else if (input.textContent != null) {
-        input.textContent = obfuscate(input.textContent!!)
+private fun obfuscate(input: Node) {
+    if (input is Element && input.hasClass("hover")) return
+    val childNodes = input.childNodes
+    if (childNodes.length > 0) {
+        childNodes.asList().forEach { obfuscate(it) }
+    }
+    if (input.nodeType == Node.TEXT_NODE) {
+        input.nodeValue = obfuscate(input.nodeValue!!)
```
Comment (kezz) [inline src/jsMain/kotlin/net/kyori/adventure/webui/js/Main.kt:559]: Could we do an `orEmpty()` here just to be safe?

**Review by kezz — APPROVED** [review]
